import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/common/Navbar';
import { UserContextProvider } from '@/context/UserContext.context';
import { ToastContextProvider } from '@/context/ToastContext.context';
import { ApolloContextProvider } from '@/context/ApolloContext.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloContextProvider>
          <UserContextProvider>
            <ToastContextProvider>
              <div id="toast" className="absolute top-16 right-4" />
              <section>
                <Navbar />
                <div className="bg-neutral-100 min-h-screen px-16">
                  {children}
                </div>
              </section>
            </ToastContextProvider>
          </UserContextProvider>
        </ApolloContextProvider>
      </body>
    </html>
  );
}
