import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/common/Navbar';
import { UserContextProvider } from '@/context/UserContext.context';
import { ToastContextProvider } from '@/context/ToastContext.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <ToastContextProvider>
            <section>
              <Navbar />
              <div>{children}</div>
            </section>
          </ToastContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
